name: Deployment
on:
  push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Linting project
        run: npm run lint
  
  test:
    name: Test
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Testing code
        run: npm test

  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Deploy app
        run: echo "Deploying app..."